### PR TITLE
DM-44660: Use runtime page URL in building websocket address

### PR DESCRIPTION
**Pull request by ugyballoons**
Hi Fred, 

This is to prepare for when the `/rubin-dev` and `/rubin` for prod URL naming comes in.
I've tested it to check that it plays nicely at `localhost` and I believe it does.

Cheers!

### CODE REVIEW

**Review by fred3m — COMMENTED** [review]
I modified the base branch so that it will just update deploy-slac. Are you sure that this works fine if `firstpath` and `address` are null? I'm worried that it will add extra slashes if either of them is ''.

**Comment by ugyballoons** [comment]
The PR is ready but there is ongoing discussion about how best to proceed with the build integration of the three repos so I'm holding back on requesting a review until that's resolved.

**Comment by ugyballoons** [comment]
> Are you sure that this works fine if `firstpath` and `address` are null? I'm worried that it will add extra slashes if either of them is ''.

It should be fine:
[https://dartpad.dev/?id=0fd52d3b5c65b179a166e025af23dc8d](https://dartpad.dev/?id=0fd52d3b5c65b179a166e025af23dc8d)

**Comment by ugyballoons** [comment]
Redundant as the project is built on the pod.

**Pull request closed without merging**
